engines:
  eslint:
    enabled: true
  env:
	  node: true
	 	mocha: true
	 	es6: true
 	ecmaFeatures:
 		modules: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/*
- !node_modules/gulp-es-next.js